from django.test import TestCase

class TestErrors(TestCase):
    
    def test_test(self):
        pass
